config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :items, :only => [:new, :create, :edit, :update], :controller => "projects/items"
    delete 'clear', :on => :member
  end
  root 'projects#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :project
  validates :action,
    :presence => true,
    :uniqueness => { :scope => :project,
                     :message => 'should be unique within a project' }
  validates :project_id, :presence => true
  scope :complete, -> { where(:done => true) }
  scope :active, -> { where(:active => true) }

  def project_title
    project.title
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, 
    :presence => true, 
    :uniqueness => {:case_sensitive => false}
  has_many :items
  scope :active, -> { where(:active => true) }

  def active_items
    items.active
  end

  def deactivate_items
    active_items.complete.update_all(:active => false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ItemNotice
  include ErrorFormatter
  before_filter :get_project

  def new
    @item = @project.items.build
  end

  def create
    @item = @project.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to project_path(@project),
                      :notice => ItemNotice::CREATE_SUCCESS }
      else
        flash[:error] = ErrorFormatter.format(@item.errors)
        format.html { render :action => 'new' }
      end
    end
  end

  def edit
    @item = @project.items.find(params[:id])
  end

  def update
    @item = @project.items.find(params[:id])

    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to project_path(@project),
                      :notice => ItemNotice::UPDATE_SUCCESS }
      else
        flash[:error] = ErrorFormatter.format(@item.errors)
        format.html { render :action => 'edit' }
      end
    end
  end

private

  def get_project
    @project = Project.find(params[:project_id])
  end

  def item_params
    params.require(:item).permit(:action, :done)
  end
end

app/controllers/projects/items_controller.rb
class Projects::ItemsController < ApplicationController
  include ItemNotice
  include ErrorFormatter
  before_filter :get_project

  def new
    @item = @project.items.build
  end

  def create
    @item = @project.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to project_path(@project),
                      :notice => ItemNotice::CREATE_SUCCESS }
      else
        flash[:error] = ErrorFormatter.format(@item.errors)
        format.html { render :action => 'new' }
      end
    end
  end

  def edit
    @item = @project.items.find(params[:id])
  end

  def update
    @item = @project.items.find(params[:id])

    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to project_path(@project),
                      :notice => ItemNotice::UPDATE_SUCCESS }
      else
        flash[:error] = ErrorFormatter.format(@item.errors)
        format.html { render :action => 'edit' }
      end
    end
  end

private

  def get_project
    @project = Project.find(params[:project_id])
  end

  def item_params
    params.require(:item).permit(:action, :done)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ProjectNotice
  include ErrorFormatter
  before_action :set_project, :except => [:index, :new, :create]

  def index
    @projects = Project.active
  end

  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.active?
        format.html { render :action => 'show' }
      else
        flash[:error] = ProjectNotice::INACTIVE_PROJECT
        format.html { redirect_to projects_path }
      end
    end
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_path(@project),
                      :notice => ProjectNotice::CREATE_SUCCESS }
      else
        flash[:error] = ErrorFormatter.format(@project.errors) 
        format.html { render :action => 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_path(@project),
                      :notice => ProjectNotice::UPDATE_SUCCESS }
      else
        flash[:error] = ErrorFormatter.format(@project.errors) 
        format.html { render :action => 'edit' }
      end
    end
  end

  def destroy
    @project.update_attribute(:active, false)
    respond_to do |format|
      format.html { redirect_to projects_path,
                    :notice => ProjectNotice::DESTROY_SUCCESS }
    end
  end

  def clear
    deactivated_items_count = @project.deactivate_items
    if deactivated_items_count > 0
      flash[:notice] = ProjectNotice::ITEMS_CLEARED 
    else
      flash[:error] = ProjectNotice::NO_ITEMS_TO_CLEAR 
    end
    respond_to do |format|
      format.html { redirect_to project_path(@project) }
    end
  end

private
  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <!--[if lt IE 9]>
    <script src="http://html5.shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <title>Tada! Todo List</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "To-Do-List", projects_path, :class => "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "All Projects", projects_path %></li>
        <li><%= link_to "New Project", new_project_path %></li>
      </ul>
    </div>
  </div>
</nav>
    </header>

    <div id="main" class="row">
      <div class="col-md-8 col-md-offset-4">
        <div class="row">
          <div class="col-md-8 flash-notice">
            <% if flash[:notice] %>
              <p id="notice" class="alert alert-success"><%= flash[:notice] %></p>
            <% end %>
            <% if flash[:error] %>
              <p id="error" class="alert alert-danger"><%= flash[:error] %></p>
            <% end %>
          </div>
        </div>
      <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project, :html => {:class => "form-inline"}) do |f| %>
  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :size => "80", :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="row">
  <h2 class="col-md-offset-2">Projects</h2>
</div>

<% if @projects.empty? %>
  <div class='row'>
    <div class='col-md-4'>
      No project to display
    </div>
  </div>
<% else %>
  <% @projects.each do |project| %>
    <div class='row project-row'>
      <div class='col-md-3 project-name text-right'>
        <%= project.title %>
      </div>
      <div class='button-inline'>
        <%= button_to 'See Items', project_path(project),
          :method => :get,
          :class => 'btn btn-sm btn-primary'%>
      </div>
      <div class='button-inline'>
        <%= button_to 'Edit', edit_project_path(project),
          :method => :get,
          :class => 'btn btn-sm btn-secondary' %>
      </div>
      <div class='button-inline'>
        <%= button_to 'Destroy', project,
          :method => :delete, :data => { :confirm => 'Are you sure?' },
          :class => 'btn btn-sm btn-warning' %>
      </div>
    </div>
  <% end %>
<% end %>

<div class='row new-project-row'>
  <div class='col-md-3 col-md-offset-7'>
    <%= button_to 'New Project', new_project_path,
      :method => :get,
      :class => 'btn btn-sm btn-success'%>
  </div>
</div>

app/views/projects/items/_form.html.erb
<%= form_for([@project, @item], :html => {:class => "form-inline"}) do |f| %>
  <div class="field form-group">
    <%= f.label :action %><br>
    <%= f.text_field :action, :size => "80", :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/projects/items/_index.html.erb
<div class="col-md-8" id="items-list">
  <% if @project.active_items.empty? %>
    <div>No items.</div>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>Item Name</th>
        </tr>
      </thead>
      <tbody>
        <% @project.active_items.each do |item| %>
          <tr>
            <td class=<%="#{item.done? ? "done" : "not-done"}"%>><%= item.action %></td>
            <% unless item.done? %>
              <td>
                <div class="button-inline">
                  <%= button_to "Done", 
                    project_item_path(@project, item, :item => { :done => true }),
                    :method => :put, :class => "btn btn-primary btn-sm"
                  %>
                </div>
                <div class="button-inline">
                  <%= button_to "Edit", edit_project_item_path(@project, item),
                    :method => :get, :class => "btn btn-sm btn-secondary" %>
                </div>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <div class="row items-buttons">
    <%= button_to "Clear Completed Items", clear_project_path(project),
      :method => :delete, :id => "clearer",
      :class => "btn btn-sm btn-secondary btn col-md-3" %>
    <%= button_to "New Item", new_project_item_path(project), 
      :method => :get, :class => "btn btn-success btn-sm col-md-2 col-md-offset-6 new-item" %>
  </div>
</div>

app/views/projects/items/edit.html.erb
<h2>Edit Item</h2>

<%= render 'form' %>

app/views/projects/items/new.html.erb
<h2>New Item</h2>

<%= render 'form' %>

app/views/projects/new.html.erb
<div class="new-project">
  <h3>New project</h3>

  <%= render 'form' %>
<div>

app/views/projects/show.html.erb
<h2><%= "#{@project.title} list" %></h2>
<%= render :partial => 'projects/items/index', :locals => { :project => @project } %>